<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Infrastructure\AuthSafe.Infrastructure.CrossCutting\AuthSafe.Infrastructure.CrossCutting.csproj" />
    <ProjectReference Include="..\AuthSafe.DomainService\AuthSafe.DomainService.csproj" />
  </ItemGroup>

</Project>
